---
# Install Kibana packages on debian based distributions.

- name: Add Kibana apt key.
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present

- name: Install apt-transport-https dependency.
  apt: name=apt-transport-https update_cache=yes state=latest install_recommends=no

- name: Install Kibana repository.
  apt_repository: repo='deb http://packages.elastic.co/kibana/5.0.0-alpha/debian stable main' state=present

- name: Install Kibana packages.
  apt: name=kibana update_cache=yes state=latest install_recommends=no

- name: Configure Kibana.
  include: kibana.yml