---
# tasks file for kibana-packages

- name: Stop the Kibana service.
  service: name=kibana state=stopped
  ignore_errors: true

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'